# Matrix build types:
#   Production: Only runs the build, not a tarball build. Called "production" because it's the part
#     used to produce tarballs. Some platforms might not be capable of producing a tarball yet: we
#     still call this type of build "production" for consistency.
#   Online: The leg produces a tarball then builds it while connected to the internet.
#   Offline: The leg produces a tarball then builds it offline. Network disconnected using Docker.

parameters:
  job: null
  imageName: null
  reportPrebuiltLeaks: false
  types:
  - Production

stages:
- ${{ each type in parameters.types }}
  - stage: ${{ format('{0} {1}', parameters.job, type)}}
    jobs:
    - template: ../jobs/ci-linux.yml
      parameters:
        job: ${{ parameters.job }}
        imageName: ${{ parameters.imageName }}
        reportPrebuiltLeaks: ${{ parameters.reportPrebuiltLeaks }}
        type: ${{ type }}
